---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-ephemeral-storage-exporter.serviceAccountName" . }}
  labels:
    {{- include "kube-ephemeral-storage-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

