replicaCount: 1

image:
  repository: kube-ephemeral-storage-exporter
  pullPolicy: IfNotPresent
  tag: ""

refreshInterval: 60
plainLogs: false


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  annotations: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9000

resources: {}

serviceMonitor:
  enabled: true
  selector: []

nodeSelector: {}

tolerations: []

affinity: {}
