# -- Number of replicas to run. There n oreason to run more than one replica as this pod requests kube-api-server to grab data;
replicaCount: 1

# -- Docker image to use
image:
  repository: kube-ephemeral-storage-exporter
  pullPolicy: IfNotPresent
  tag: ""

# -- Refresh interval (in seconds) to re-read the metrics values.
refreshInterval: 60

# -- Turn on plain logs. By defult logs are in JSON format
plainLogs: false


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  annotations: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9000

resources: {}

# -- Additional labels
labels: {}

serviceMonitor:
  # -- Enable serviceMonitor CRD creation
  enabled: "true"
  selector: []

nodeSelector: {}

tolerations: []

affinity: {}
